language: typescript
# # nodejs版本
node_js: 
    - stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build

after_success:
  # - cd ./dist
  - git init
  - git config user.name "wqlchenxiang"
  - git config user.email "mylovewang2013"
  - git add .
  - git commit -m "update bundles"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
  # git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# # E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/wqlchenxiang/hello-world.git