language: typescript
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
before_script: 
script:
- npm run build
after_success:
- git init
- git config user.name "wqlchenxiang"
- git config user.email "m18510176015@163.com"
- git add .
- git commit -m "update bundles"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/wqlchenxiang/hello-world.git
deply:
  github-token:
    secure: IRMyyiCzraqp2eL9aHfQt8CzjjABhhYP78RvtH5nK+j6hWXIZ8Jyj0vAtZIzjOPy2xdWYHAtTnkE06r4yJ2a6CtBBKdu4VfgpnV4DGADXJng0X8NqXS8W+PCsBbaWZfnQO3iCbtAck31dIshUjgS6NoDAaL38ozBsS5HnJgC14ysMsvOcwTmXytj/Ey5oDiPAF4er+EcE+BupefejY9++PpLuLCpAwZ1D9oEsSoBybmnlHuyPXFvry2SSG5i9hMBFrqnLh2iZzhPi/DKMDTz50F0mokhrDtGEQje3QuVDzoV3ty2oorngHhX3wXQadfOiRc6tf/LzlOg1dU4h0N9bSWuSxbS4jVkeoD8OcuuGbfDNk9hJUfrM8KH8HAEX/H0SdVeyPMXXE/sW23QYXAI4gQw02o8jCULwSiLqch5Llsg5WXQiPkQxJvKiNG0jOWGEy5eG1XqcLxIUYGs55R8q+2auKNmRIj0jzsubTyyVFng41uk/aAKWqKyHSc6EpdK5TdhQEOAnyizDXvU/HV3EOMQQ+NILyO3NCsSFfz9cbA+W1mlbrBFhn+6Q/tVjoBLbTbOL73Dmj9pQOSaOW+soLeJQXDmhLvkFVN+HimxXsMytWZlbRhVMrJcG79DOFuHIyVshl9zoZ2h9q2xqxIaZMHuKCVrpGAWWJEpSHpcdlA=
